version: '3.9'

services:

  bank-pipeline:

    build: .

    container_name: bank_marketing_pipeline

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    command: >
      sh -c "
      python scripts/ingest/ingestion_data.py &&
      python scripts/cleaning/cleaning_data.py &&
      python scripts/transform/transform_data.py &&
      python scripts/validation/validation_data.py &&
      python scripts/load/loading_data.py
      "