name: Bank Marketing Pipeline

on:
  push:
    branches:
      - main

jobs:

  etl-pipeline:

    runs-on: ubuntu-latest

    steps:

      # ============================================
      # CLONAR REPOSITORIO
      # ============================================

      - name: Checkout repository
        uses: actions/checkout@v4

      # ============================================
      # INSTALAR PYTHON
      # ============================================

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ============================================
      # INSTALAR DEPENDENCIAS
      # ============================================

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ============================================
      # CREAR ARCHIVO .ENV
      # ============================================

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      # ============================================
      # EJECUTAR INGESTA
      # ============================================

      - name: Run ingestion
        run: |
          python scripts/ingest/ingestion_data.py

      # ============================================
      # EJECUTAR LIMPIEZA
      # ============================================

      - name: Run cleaning
        run: |
          python scripts/cleaning/cleaning_data.py


      # ============================================
      # EJECUTAR TRANSFORMACIÓN
      # ============================================

      - name: Run transformation
        run: |
          python scripts/transform/transform_data.py

      # ============================================
      # EJECUTAR VALIDACIÓN
      # ============================================

      - name: Run validation
        run: |
          python scripts/validation/validation_data.py

      # ============================================
      # EJECUTAR CARGA
      # ============================================

      - name: Run loading
        run: |
          python scripts/load/loading_data.py